export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const RESET_USER_BEGIN = "RESET_USER_BEGIN";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";
export const RESET_USER_ERROR = "RESET_USER_ERROR";

export const ADD_USER_BEGIN = "ADD_USER_BEGIN";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const VERIFY_USER_BEGIN = "VERIFY_USER_BEGIN";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_ERROR = "VERIFY_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const ADD_NOTES_BEGIN = "ADD_NOTES_BEGIN";
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_ERROR = "ADD_NOTES_ERROR";

export const GET_NOTES_BEGIN = "GET_NOTES_BEGIN";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const SET_EDIT_NOTE = "SET_EDIT_NOTE";
export const EDIT_NOTE_BEGIN = "EDIT_NOTE_BEGIN";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_ERROR = "EDIT_NOTE_ERROR";

export const DELETE_NOTE_BEGIN = "DELETE_NOTE_BEGIN";
